name: 👩‍💻 Inserts Recent Activity
on:
  schedule:
    # Runs at the end of every day.
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Adds activity to Readme (EN)
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: ':zap: Updates recent activity'
        with:
          CONFIG_FILE: "./.github/recent-activity-config/en-readme.config.yml"

      - name: Adds activity to file (EN)
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: ':zap: Updates recent activity'
        with:
          CONFIG_FILE: "./.github/recent-activity-config/en-file.config.yml"

      - name: Adds activity to Readme (RU)
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: ':zap: Updates recent activity'
        with:
          CONFIG_FILE: "./.github/recent-activity-config/ru-readme.config.yml"

      - name: Adds activity to file (RU)
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: ':zap: Updates recent activity'
        with:
          CONFIG_FILE: "./.github/recent-activity-config/ru-file.config.yml"
